version: '3.7'

services:
  dash_db:
    container_name: "dash_db"
    image: "postgres:12-alpine"
    restart: unless-stopped
    volumes:
      - dash_db:/var/lib/postgresql
    environment:
      - POSTGRES_USER=dashuser
      - POSTGRES_PASSWORD=dashpassword
      - POSTGRES_DB=dash
    networks:
      - dash_network

  dash_app:
    container_name: "dash_app"
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - example.env
    environment:
      - DB_TYPE=el
    ports:
      - 8000:8000
    depends_on:
      - dash_db
    networks:
      - dash_network

# volumes definiton
volumes:
  dash_db:

# network definition
networks:
  dash_network:
    driver: bridge
